### ISSUE TITLE
Error using step function

### ISSUE THREAD

**Issue by BiswanathPanda** [benubah/control#1]
Using the step function to plot the step response of a transfer function gives this error message.
  

> Error

  Error in balance(baP$z, "S") : 
  BLAS/LAPACK routine 'DGEBAL' gave error code -3

**Comment by benubah** [comment]
Can you show your usage of the `step` function? What parameters did you pass to it?
I cannot reproduce your issue unless you can show how you were using `step` before it threw the error message - the exact code example that causes this problem.

**Comment by BiswanathPanda** [comment]
library(control)
kt<-0.06
j<-0.001
b<-0.01
r<-1
kb<-0.06
sys<- tf(c(0,kt),c(0,j*r,((b*r)+(kt*kb))))
print(sys)
step(sys)


This was the exact code i used.

**Comment by benubah** [comment]
Very well.
Try this instead and let me know if it resolves:
`sys<- tf(c(kt),c(j*r,((b*r)+(kt*kb))))`
`print(sys)`
`step(sys)`
`stepplot(sys)`

**Comment by BiswanathPanda** [comment]
Sir it gave the same error.

**Comment by BiswanathPanda** [comment]
Error
Error in balance(baP$z, "S") :
BLAS/LAPACK routine 'DGEBAL' gave error code -3

**Comment by benubah** [comment]
![image](https://user-images.githubusercontent.com/11357251/29647811-01193674-8883-11e7-94c8-d046f67c9164.png)
Try clearing your workspace and run this - this works for me:
`kt<-0.06 `
`j<-0.001` 
`b<-0.01`
`r<-1 `
`kb<-0.06 `
`sys<- tf(c(kt),c(j*r,((b*r)+(kt*kb))))`
`print(sys) `
`stepplot(sys)`

**Comment by BiswanathPanda** [comment]
Sir, is there something wrong with my updating of the control package? Should I update it again using this code?

> install.packages("devtools")
    library(devtools)
    install_github("benubah/control")

**Comment by BiswanathPanda** [comment]
Thank you sir!!! Now I m getting the response.

**Comment by benubah** [comment]
Ok.
And also try this alternative:
![image](https://user-images.githubusercontent.com/11357251/29648075-466dacf4-8884-11e7-9533-b8e80f71aefe.png)

`kt<-0.06 `
`j<-0.001 `
`b<-0.01`
`r<-1 `
`kb<-0.06` 
`sys2 <- TF("kt/(j*r*s + (b*r + kt*kb))")`
`print(sys2)`
`stepplot(sys2)`

**Comment by BiswanathPanda** [comment]
Yes Sir. Thank you.
