### ISSUE TITLE
the results of control::place are different from place function in Matlab

### ISSUE THREAD

**Issue by jywang2016** [benubah/control#2]
Hi

Thanks for your work in `Control` package. It seems the results of `place()` example cannot be reproduced by Matlab place function.

Here is the code of `place` example:

```
F <- rbind(c(0,1),c(0,0))
G <- rbind(0,1)
H <- cbind(1,0);
J <- 0
t <- 1
sys  <-  ss(F,G, H,J)
A  <-  c2d(sys,t);
j <- sqrt(as.complex(-1));
pc  <- rbind(0.78+0.18*j, 0.78-0.18*j)
K  <-  place(A$A, A$B, pc)
```

And the results just like the follows:

```
> K
        [,1]
[1,] -0.0808
[2,] -0.3188
```

But in Matlab, the results are different:

```
F = [0,1;0,0];
G = [0;1];
H = [1,0];
J = [0];
t = 1;
sys = ss(F,G,H,J);
sysd = c2d(sys,t);
pc = [0.78+0.18*sqrt(-1);0.78-0.18*sqrt(-1)];
place(sysd.A,sysd.B,pc)'

ans =

    0.0808
    0.3996
```
I really want to know where the problem lies since I am a green hand in control filed .  I would greatly appreciate any suggestions.

Regards

JY

**Comment by benubah** [comment]
Thanks for pointing this out and apologies for delayed response.

`place` in this `control` package uses Ackermann's formula while `place` in Matlab uses a different algorithm (please see References section at Matlab's web page for this: https://www.mathworks.com/help/control/ref/place.html)

So the results could slightly differ depending on the case.

**Comment by jywang2016** [comment]
Thanks for your reply. 👍
